jobs:
  - job: RunWindowsTests_1_CreateTypespecProject
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "22.17.0"
        displayName: "Install Node.js"

      - script: |
          npm install
        displayName: "Install dependencies"

      - script: |
          echo "Running Create Test Cases"
          npm run test:create
        displayName: "Run Create Test Cases"
        env:
          BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
          CI: true
        continueOnError: true

      - task: PublishBuildArtifacts@1
        inputs:
          path: "$(Build.ArtifactStagingDirectory)"
          artifact: "screenshots"
          publishLocation: "Container"
          includePatterns: "images-windows/**/*.png"
        displayName: "Publish screenshots to Artifacts"

  - job: RunWindowsTests_2_EmitTypespecProject
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "22.17.0"
        displayName: "Install Node.js"

      - task: UseDotNet@2
        inputs:
          packageType: "sdk"
          version: "8.0.204"
        displayName: "Install .NET SDK"

      - script: |
          wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
          tar -xzf apache-maven-3.9.6-bin.tar.gz -C /usr/local/
          echo 'export PATH="/usr/local/apache-maven-3.9.6/bin:$PATH"' >> ~/.bashrc
          mvn -v
        displayName: "Install Maven"

      - script: |
          npm install
        displayName: "Install dependencies"

      - script: |
          echo "Running Emit Test Cases"
          npm run test:emit
        displayName: "Run Emit Test Cases"
        env:
          BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
          CI: true
          JAVA_HOME: $(JAVA_HOME_21_X64)
          PATH: $(JAVA_HOME_21_X64)\bin;$(PATH)
        continueOnError: true

      - task: PublishBuildArtifacts@1
        inputs:
          path: "$(Build.ArtifactStagingDirectory)"
          artifact: "screenshots"
          publishLocation: "Container"
          includePatterns: "images-windows/**/*.png"
        displayName: "Publish screenshots to Artifacts"

  - job: RunWindowsTests_3_ImportTypespecProject
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "22.17.0"
        displayName: "Install Node.js"

      - script: |
          npm install
        displayName: "Install dependencies"

      - script: |
          echo "Running Import Test Cases"
          npm run test:import
        displayName: "Run Import Test Cases"
        env:
          BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
          CI: true
        continueOnError: true

      - task: PublishBuildArtifacts@1
        inputs:
          path: "$(Build.ArtifactStagingDirectory)"
          artifact: "screenshots"
          publishLocation: "Container"
          includePatterns: "images-windows/**/*.png"
        displayName: "Publish screenshots to Artifacts"

  - job: RunWindowsTests_4_PreviewTypespecProject
    pool:
      vmImage: "windows-latest"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "22.17.0"
        displayName: "Install Node.js"

      - script: |
          npm install
        displayName: "Install dependencies"

      - script: |
          echo "Running Preview Test Cases"
          npm run test:preview
        displayName: "Run Preview Test Cases"
        env:
          BUILD_ARTIFACT_STAGING_DIRECTORY: $(Build.ArtifactStagingDirectory)
          CI: true
        continueOnError: true

      - task: PublishBuildArtifacts@1
        inputs:
          path: "$(Build.ArtifactStagingDirectory)"
          artifact: "screenshots"
          publishLocation: "Container"
          includePatterns: "images-windows/**/*.png"
        displayName: "Publish screenshots to Artifacts"
