emit:
  - "@typespec/http-client-java"
  - "@typespec/http-client-js"
  - "@typespec/http-client-csharp"
options:
  "@typespec/http-client-java":
    emitter-output-dir: "{output-dir}/{emitter-name}"
  "@typespec/http-client-js":
    emitter-output-dir: "{output-dir}/{emitter-name}"
  "@typespec/http-client-csharp":
    emitter-output-dir: "{output-dir}/{emitter-name}"
